// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmvJ5s4yUZXOU1ftXuh7yatCo-6MONcBE',
    appId: '1:614790011906:web:6b2a10a35b87ada1d09b1b',
    messagingSenderId: '614790011906',
    projectId: 'trainingapp-c0f06',
    authDomain: 'trainingapp-c0f06.firebaseapp.com',
    storageBucket: 'trainingapp-c0f06.appspot.com',
    measurementId: 'G-HT50WGZSB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGcYEpQKQoQPbEs9nmmpRzYFTLxCEnKx4',
    appId: '1:614790011906:android:be4482912471f7f9d09b1b',
    messagingSenderId: '614790011906',
    projectId: 'trainingapp-c0f06',
    storageBucket: 'trainingapp-c0f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVVUP6jhuRmx_iW_5wft2jOhyqKB7IyD0',
    appId: '1:614790011906:ios:a8a32a022f70e89cd09b1b',
    messagingSenderId: '614790011906',
    projectId: 'trainingapp-c0f06',
    storageBucket: 'trainingapp-c0f06.appspot.com',
    iosClientId: '614790011906-vvf2qechgv0foeddb6d3lovet2vaiouj.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVVUP6jhuRmx_iW_5wft2jOhyqKB7IyD0',
    appId: '1:614790011906:ios:a8a32a022f70e89cd09b1b',
    messagingSenderId: '614790011906',
    projectId: 'trainingapp-c0f06',
    storageBucket: 'trainingapp-c0f06.appspot.com',
    iosClientId: '614790011906-vvf2qechgv0foeddb6d3lovet2vaiouj.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp',
  );
}
